import json
import os
import urllib.request
import logging

# Configure logger
logger = logging.getLogger()
logger.setLevel(logging.INFO)

def lambda_handler(event, context):
    logger.info(f"Tavily search initiated for path: {event.get('apiPath')}")
    # Bedrock Agent Action Group payloads look for 'apiPath' and 'parameters'.
    
    tavily_secret_arn = os.environ.get("TAVILY_SECRET_ARN")
    tavily_api_key = None
    if tavily_secret_arn:
        try:
            import boto3
            secrets_client = boto3.client('secretsmanager')
            secret_val = secrets_client.get_secret_value(SecretId=tavily_secret_arn)
            tavily_api_key = secret_val.get('SecretString')
        except Exception as e:
            logger.error(f"Failed to retrieve Tavily secret from Secrets Manager: {e}")
            
    search_query = "Unknown"
    
    request_body = event.get('requestBody', {}).get('content', {}).get('application/json', {}).get('properties', [])
    for prop in request_body:
        if prop.get('name') == 'query':
            search_query = prop.get('value')

    logger.info(f"Searching Tavily for query: {search_query}")
    
    if not tavily_api_key:
        search_result = "TAVILY_API_KEY is not set or failed to load."
        logger.warning("TAVILY_API_KEY is missing or secret retrieval failed.")
    else:
        req_body = json.dumps({
            "api_key": tavily_api_key,
            "query": search_query,
            "search_depth": "basic",
            "include_answer": True,
            "max_results": 10
        }).encode('utf-8')
        
        req = urllib.request.Request(
            "https://api.tavily.com/search",
            data=req_body,
            headers={"Content-Type": "application/json"}
        )
        
        try:
            with urllib.request.urlopen(req) as response:
                result_data = json.loads(response.read().decode('utf-8'))
                search_result = result_data.get("answer") or "No answer generated by Tavily."
                if not result_data.get("answer"):
                    # Fallback to appending results
                    results = result_data.get("results", [])
                    search_result = "\n".join([f"- {r.get('title')}: {r.get('content')}" for r in results[:10]])
        except Exception as e:
            logger.error(f"Error calling Tavily API: {str(e)}")
            search_result = f"Failed to search Tavily: {e}"
    
    response_body = {
        "application/json": {
            "body": json.dumps({"search_result": search_result})
        }
    }
    
    action_response = {
        "actionGroup": event.get("actionGroup"),
        "apiPath": event.get("apiPath"),
        "httpMethod": event.get("httpMethod"),
        "httpStatusCode": 200,
        "responseBody": response_body
    }
    
    # Bedrock format response
    return {"messageVersion": "1.0", "response": action_response}
