name: Deploy Odoo to AWS via Terraform

on:
  workflow_dispatch:

env:
  AWS_REGION: ap-south-1
  ODOO_ECR_REPOSITORY: odoo-custom
  NGINX_ECR_REPOSITORY: nginx-custom

# Added id-token: write here, which is required for OIDC!
permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v6
      with:
        role-to-assume: ${{ vars.AWS_OIDC_ROLE_ARN }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v4

    - name: Setup Docker Buildx
      uses: docker/setup-buildx-action@v4

    - name: Terraform Init
      working-directory: ./terraform
      run: terraform init

    - name: Create ECR Repositories via Terraform
      working-directory: ./terraform
      run: |
        terraform apply -auto-approve \
          -target="aws_ecr_repository.odoo" \
          -target="aws_ecr_repository.nginx" \
          -var="odoo_image_url=dummy" \
          -var="nginx_image_url=dummy"

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push Odoo image
      id: build-odoo
      uses: docker/build-push-action@v7
      with:
        context: .
        file: templates/Dockerfile.odoo
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.ODOO_ECR_REPOSITORY }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Build, tag, and push Nginx image
      id: build-nginx
      uses: docker/build-push-action@v7
      with:
        context: .
        file: templates/Dockerfile.nginx
        push: true
        tags: ${{ steps.login-ecr.outputs.registry }}/${{ env.NGINX_ECR_REPOSITORY }}:${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Terraform Apply
      working-directory: ./terraform
      run: |
        terraform apply -auto-approve \
          -var="odoo_image_url=${{ steps.login-ecr.outputs.registry }}/${{ env.ODOO_ECR_REPOSITORY }}:${{ github.sha }}" \
          -var="nginx_image_url=${{ steps.login-ecr.outputs.registry }}/${{ env.NGINX_ECR_REPOSITORY }}:${{ github.sha }}"
